prueba/Models/ErrorViewModel.cs
namespace prueba.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

prueba/Models/Presupuesto.cs
using System;
using System.Collections.Generic;

namespace prueba.Models;

public partial class Presupuesto
{
    public int PresupuestoId { get; set; }

    public string? Unidad { get; set; }

    public string? TipoBienServicio { get; set; }

    public string? Cantidad { get; set; }

    public string? ValorUnitario { get; set; }

    public string? ValorTotal { get; set; }

    public string? FechaAdquision { get; set; }

    public string? Proveedor { get; set; }

    public string? Documentacion { get; set; }
}

prueba/Models/PruebaContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace prueba.Models;

public partial class PruebaContext : DbContext
{
    public PruebaContext()
    {
    }

    public PruebaContext(DbContextOptions<PruebaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Presupuesto> Presupuestos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {

    }
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
 //       => optionsBuilder.UseSqlServer("server=localhost\\SQLEXPRESS; database=prueba; Encrypt=false; integrated security=true; TrustServerCertificate=true");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Presupuesto>(entity =>
        {
            entity.HasKey(e => e.PresupuestoId).HasName("PK__presupue__DAAAB25C24A246F5");

            entity.ToTable("presupuesto");

            entity.Property(e => e.PresupuestoId).HasColumnName("presupuesto_id");
            entity.Property(e => e.Cantidad)
                .HasMaxLength(100)
                .HasColumnName("cantidad");
            entity.Property(e => e.Documentacion)
                .HasMaxLength(100)
                .HasColumnName("documentacion");
            entity.Property(e => e.FechaAdquision)
                .HasMaxLength(100)
                .HasColumnName("fechaAdquision");
            entity.Property(e => e.Proveedor)
                .HasMaxLength(100)
                .HasColumnName("proveedor");
            entity.Property(e => e.TipoBienServicio)
                .HasMaxLength(100)
                .HasColumnName("tipoBienServicio");
            entity.Property(e => e.Unidad)
                .HasMaxLength(100)
                .HasColumnName("unidad");
            entity.Property(e => e.ValorTotal)
                .HasMaxLength(100)
                .HasColumnName("valorTotal");
            entity.Property(e => e.ValorUnitario)
                .HasMaxLength(100)
                .HasColumnName("valorUnitario");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

prueba/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using prueba.Models;

namespace prueba.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

prueba/Controllers/PresupuestoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using prueba.Models;

namespace prueba.Controllers
{
    public class PresupuestoesController : Controller
    {
        private readonly PruebaContext _context;

        public PresupuestoesController(PruebaContext context)
        {
            _context = context;
        }

        // GET: Presupuestoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Presupuestos.ToListAsync());
        }

        // GET: Presupuestoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var presupuesto = await _context.Presupuestos
                .FirstOrDefaultAsync(m => m.PresupuestoId == id);
            if (presupuesto == null)
            {
                return NotFound();
            }

            return View(presupuesto);
        }

        // GET: Presupuestoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Presupuestoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PresupuestoId,Unidad,TipoBienServicio,Cantidad,ValorUnitario,ValorTotal,FechaAdquision,Proveedor,Documentacion")] Presupuesto presupuesto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(presupuesto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(presupuesto);
        }

        // GET: Presupuestoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var presupuesto = await _context.Presupuestos.FindAsync(id);
            if (presupuesto == null)
            {
                return NotFound();
            }
            return View(presupuesto);
        }

        // POST: Presupuestoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PresupuestoId,Unidad,TipoBienServicio,Cantidad,ValorUnitario,ValorTotal,FechaAdquision,Proveedor,Documentacion")] Presupuesto presupuesto)
        {
            if (id != presupuesto.PresupuestoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(presupuesto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PresupuestoExists(presupuesto.PresupuestoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(presupuesto);
        }

        // GET: Presupuestoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var presupuesto = await _context.Presupuestos
                .FirstOrDefaultAsync(m => m.PresupuestoId == id);
            if (presupuesto == null)
            {
                return NotFound();
            }

            return View(presupuesto);
        }

        // POST: Presupuestoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var presupuesto = await _context.Presupuestos.FindAsync(id);
            if (presupuesto != null)
            {
                _context.Presupuestos.Remove(presupuesto);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PresupuestoExists(int id)
        {
            return _context.Presupuestos.Any(e => e.PresupuestoId == id);
        }
    }
}

prueba/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <img src="~/Captura de pantalla 2025-03-20 085310.jpg" alt="Descripción de la imagen" width="500" height="300">
</div>

prueba/Views/Presupuestoes/Create.cshtml
@model prueba.Models.Presupuesto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Presupuesto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Unidad" class="control-label"></label>
                <input asp-for="Unidad" class="form-control" />
                <span asp-validation-for="Unidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoBienServicio" class="control-label"></label>
                <input asp-for="TipoBienServicio" class="form-control" />
                <span asp-validation-for="TipoBienServicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorUnitario" class="control-label"></label>
                <input asp-for="ValorUnitario" class="form-control" />
                <span asp-validation-for="ValorUnitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorTotal" class="control-label"></label>
                <input asp-for="ValorTotal" class="form-control" />
                <span asp-validation-for="ValorTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaAdquision" class="control-label"></label>
                <input asp-for="FechaAdquision" class="form-control" />
                <span asp-validation-for="FechaAdquision" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Proveedor" class="control-label"></label>
                <input asp-for="Proveedor" class="form-control" />
                <span asp-validation-for="Proveedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Documentacion" class="control-label"></label>
                <input asp-for="Documentacion" class="form-control" />
                <span asp-validation-for="Documentacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

prueba/Views/Presupuestoes/Delete.cshtml
@model prueba.Models.Presupuesto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Presupuesto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoBienServicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoBienServicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorUnitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorUnitario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorTotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorTotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaAdquision)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaAdquision)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Proveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proveedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Documentacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Documentacion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PresupuestoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

prueba/Views/Presupuestoes/Details.cshtml
@model prueba.Models.Presupuesto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Presupuesto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoBienServicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoBienServicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorUnitario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorUnitario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ValorTotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValorTotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaAdquision)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaAdquision)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Proveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proveedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Documentacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Documentacion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PresupuestoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

prueba/Views/Presupuestoes/Edit.cshtml
@model prueba.Models.Presupuesto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Presupuesto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PresupuestoId" />
            <div class="form-group">
                <label asp-for="Unidad" class="control-label"></label>
                <input asp-for="Unidad" class="form-control" />
                <span asp-validation-for="Unidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoBienServicio" class="control-label"></label>
                <input asp-for="TipoBienServicio" class="form-control" />
                <span asp-validation-for="TipoBienServicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorUnitario" class="control-label"></label>
                <input asp-for="ValorUnitario" class="form-control" />
                <span asp-validation-for="ValorUnitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValorTotal" class="control-label"></label>
                <input asp-for="ValorTotal" class="form-control" />
                <span asp-validation-for="ValorTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaAdquision" class="control-label"></label>
                <input asp-for="FechaAdquision" class="form-control" />
                <span asp-validation-for="FechaAdquision" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Proveedor" class="control-label"></label>
                <input asp-for="Proveedor" class="form-control" />
                <span asp-validation-for="Proveedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Documentacion" class="control-label"></label>
                <input asp-for="Documentacion" class="form-control" />
                <span asp-validation-for="Documentacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

prueba/Views/Presupuestoes/Index.cshtml
@model IEnumerable<prueba.Models.Presupuesto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Unidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoBienServicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorUnitario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ValorTotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaAdquision)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Proveedor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documentacion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Unidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoBienServicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorUnitario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValorTotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaAdquision)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Proveedor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Documentacion)
            </td>
            <td>
                <a asp-action="Edit"  class="btn btn-warning" asp-route-id="@item.PresupuestoId">Edit</a> |
                <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.PresupuestoId">Details</a> |
                <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.PresupuestoId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

prueba/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - prueba</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/prueba.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Presupuestoes" asp-action="Index">Presupuestos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - prueba - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>